version: 2
jobs:
  build:
    docker:
      - image: centos:7
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: install fpm building tools
          command: yum install -y ruby-devel gcc make rpm-build rubygems
      - run:
          name: install fpm
          command: gem install --no-ri --no-rdoc fpm
      - run:
          name: syscheck
          command: ./lib/release.sh --program syscheck --version $CIRCLE_SHA1
      - run:
          name: syscheck install
          command: rpm -Uvh ../syscheck*rpm
      - run:
          name: create directory for articats
          command: mkdir /tmp/artifacts
      - run:
          name: copy arifacts
          command: |
            cp ../syscheck*zip* /tmp/artifacts;
            cp ../syscheck*rpm /tmp/artifacts;
            cp ../syscheck*deb /tmp/artifacts

      - store_artifacts:
          path: /tmp/artifacts
