version: 2
jobs:
  build:
    docker:
      - image: centos:7
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: syscheck
          command: ./misc/
      - run:
          name: syscheck help
          command: ls
