version: 2
jobs:
  build:
    docker:
      - image: centos:7
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: install fpm building tools
          command: yum install -y ruby-devel gcc make rpm-build rubygems
      - run:
          name: install fpm
          command: gem install --no-ri --no-rdoc fpm
      - run:
          name: create directory for articats
          command: mkdir /tmp/artifacts
      - run:
          name: syscheck
          command: ./lib/release.sh --program syscheck --version snapshot --outpath /tmp/artifacts
      - run:
          name: syscheck install
          command: rpm -Uvh /tmp/artifacts/syscheck*rpm

      - store_artifacts:
          path: /tmp/artifacts

      - run:
          name: test help 1
          command: test/bats-core/bin/bats test/help.bats

      - run:
          name: test help 1
          command: test/bats-core/bin/bats test/help-scripts.bats

      - run:
          name: test help 1
          command: test/bats-core/bin/bats test/test-scripts.bats
