name: ci
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
      - run: sudo apt-get install ruby ruby-dev rubygems build-essential
      - run: gem install --no-document fpm
      - run: /source/test/run-build-install-and-test.sh /source /opt/syscheck /results /work

# version: 2
# jobs:
#   build:
#     docker:
#       - image: centos:7
#     steps:
#       - checkout
#       - run:
#           name: Greeting
#           command: echo Hello, world.
#       - run:
#           name: install fpm building tools
#           command: yum install -y ruby-devel gcc make rpm-build rubygems
#       - run:
#           name: install fpm
#           command: gem install --no-ri --no-rdoc fpm
#       - run:
#           name: create directory for articats
#           command: mkdir /tmp/artifacts
#       - run:
#           name: syscheck
#           command: ./lib/release.sh --program syscheck --version snapshot --outpath /tmp/artifacts
#       - run:
#           name: syscheck install
#           command: rpm -Uvh /tmp/artifacts/syscheck*rpm
#
#       - run:
#           name: set SYSCHECK_HOME
#           command: |
#             echo 'export SYSCHECK_HOME=/opt/syscheck' >> $BASH_ENV
#             source $BASH_ENV
#
#       - store_artifacts:
#           path: /tmp/artifacts
#
#       - run:
#           name: create directory for test-reports
#           command: mkdir /tmp/test-reports
#
#       - run:
#           name: test help 1
#           command: test/bats-core/bin/bats test/help.bats > /tmp/test-reports/test_1_help.txt
#       - run:
#           name: test help scritps
#           command: test/bats-core/bin/bats test/help-scripts.bats > /tmp/test-reports/test_2_help_scripts.txt
#
#       - run:
#           name: test scripts
#           command: test/bats-core/bin/bats test/test-scripts.bats > /tmp/test-reports/test_2_scripts.txt
#
#       - run:
#           name: test scripts
#           command: test/bats-core/bin/bats test/test-syscheck-console.bats > /tmp/test-reports/test_3_console.txt
